### ISSUE TITLE
Illegal key size exception

### ISSUE THREAD

**Issue by diogogmt** [rancher/cattle#1248]
When I try to build cattle v0.127.0 I get the following exception

```mvn install```
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.cattle.platform.framework.encryption.EncryptionUtilsTest
20:51:26.401 [main] INFO  c.n.c.sources.URLConfigurationSource - URLs to be used as dynamic configuration source: [file:/usr/local/rancher/cattle/code/framework/encryption/target/test-classes/config.properties]
20:51:26.462 [main] INFO  c.n.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@3dfc5fb8
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.641 sec
Running io.cattle.platform.framework.encryption.handler.impl.TransformationServiceImplTest
java.security.InvalidKeyException: Illegal key size
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
    at javax.crypto.Cipher.init(Cipher.java:1393)
    at javax.crypto.Cipher.init(Cipher.java:1327)
    at io.cattle.platform.framework.encryption.impl.Aes256Encrypter.encrypt(Aes256Encrypter.java:50)
    at io.cattle.platform.framework.encryption.Encrypter.transform(Encrypter.java:20)
    at io.cattle.platform.framework.encryption.handler.impl.TransformationServiceImpl.transform(TransformationServiceImpl.java:32)

        at io.cattle.platform.framework.encryption.handler.impl.TransformationServiceImplTest.testEncryptDecryptInValid(TransformationServiceImplTest.java:48)
```

I can build the project if the tests are disabled:
```mvn install -Dmaven.test.skip=true install```

**Comment by ibuildthecloud** [comment]
@diogogmt Can you install http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html  We need strong encryption.

**Comment by diogogmt** [comment]
@ibuildthecloud 
After downloading the UnlimitedJCEPolicy zip and copying both local_policy.jar and US_export_policy.jar to $java_path/jre/lib/security I was able to build and run all cattle tests.
Thanks.
