### ISSUE TITLE
deploying cattle.war to tomcat  occur error

### ISSUE THREAD

**Issue by Jamlee** [rancher/cattle#1348]
The error like following:
```

Cannot create JDBC driver of class '' for connect URL 'jdbc:h2:db-cattle'
java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1437)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at io.cattle.platform.archaius.sources.LazyJDBCSource.checkInitial(LazyJDBCSource.java:50)
	at io.cattle.platform.archaius.sources.LazyJDBCSource.poll(LazyJDBCSource.java:34)
	at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163)
	at io.cattle.platform.archaius.polling.RefreshableFixedDelayPollingScheduler.refresh(RefreshableFixedDelayPollingScheduler.java:34)
	at io.cattle.platform.archaius.startup.ArchaiusStartup.load(ArchaiusStartup.java:91)
	at io.cattle.platform.archaius.startup.ArchaiusStartup.start(ArchaiusStartup.java:68)
	at io.cattle.platform.extension.spring.BackgroundStart.run(BackgroundStart.java:63)
```

but I sure that h2-*.jar is in my `WEB_INF/lib` dir.

![image](https://cloud.githubusercontent.com/assets/5196641/12917793/849cdc8e-cf76-11e5-9dcb-280bb0e3a910.png)

**Comment by ibuildthecloud** [comment]
I just wanted to forwarn you that our WebSocket implementation is tied to Jetty: https://github.com/rancher/cattle/blob/master/code/framework/api-pub-sub-jetty/src/main/java/io/cattle/platform/api/pubsub/subscribe/jetty/JettyWebSocketSubcriptionHandler.java

I'd love to see a generic implementation that wasn't tied to Jetty, but we only had time to get that working.

But... please try setting an environment variable CATTLE_HOME or a Java system property name cattle.home that points to a directory in which the H2 database will be stored.  That may resolve your issue.
