### ISSUE TITLE
Agent startup: Failed downloads, "gzip: stdin: not in gzip format" and other errors

### ISSUE THREAD

**Issue by bentolor** [rancher/cattle#792]
I'm trying to deploy rancher in a very simple toy project and running in all sorts of issues.

Trying to add a new custom host via CLI statement: `sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.11 http://n179:8080/v1/scripts/<key>:<x>:y>`

Host eventually does appear, but simple tasks like starting a container or adding a load balancer service do not work and lead to an endless loop.

Any hints? Known issue?

`sudo docker logs -f rancher-agent` reveals the following ouput/errors 

```
INFO: Starting agent for 062B0EE4DFBAC3F5895F
..
INFO: Using image rancher/agent:v0.7.11
INFO: Downloading agent http://n179:8080/v1/configcontent/configscripts
...
INFO: Updating agent-binaries
INFO: Downloading https://github.com/rancher/agent-binaries/releases/download/v0.1.2/agent-binaries.tar.gz current=

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[[scripts.sh:198] docker_env
...
[scripts.sh:45] curl -s --connect-timeout 3 -L 'https://github.com/rancher/agent-binaries/releases/download/v0.1.2/agent-binaries.tar.gz?current='
[config.sh:121] tar xzf /var/lib/cattle/download.c8kBjKA/download -C /var/lib/cattle/download.c8kBjKA

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[config.sh:1] cleanup
[config.sh:9] EXIT=2
...
INFO: Updating volmgr
INFO: Downloading https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz current=

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[[scripts.sh:198] docker_env
...
[config.sh:118] info Downloading https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz current=
[scripts.sh:33] echo INFO: Downloading https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz current=
INFO: Downloading https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz current=
[config.sh:120] get --no-auth 'https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz?current='
[scripts.sh:57] '[' --no-auth = --no-auth ']'
[scripts.sh:58] shift 1
[scripts.sh:59] CURL_AUTH=false
[scripts.sh:59] call_curl -L 'https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz?current='
[scripts.sh:43] local 'curl=curl -s --connect-timeout 3'
[scripts.sh:44] '[' false = false ']'
[scripts.sh:45] curl -s --connect-timeout 3 -L 'https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz?current='
[config.sh:121] tar xzf /var/lib/cattle/download.TQbwE37/download -C /var/lib/cattle/download.TQbwE37

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[config.sh:1] cleanup
...
INFO: Updating volmgr
INFO: Downloading https://github.com/rancher/rancher-volume/releases/download/v0.1.5/volmgr.tar.gz current=

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[[scripts.sh:198] docker_env
....
INFO: Updating volmgr
[config.sh:250] UPTODATE=false
[config.sh:251] download volmgr
[config.sh:82] cleanup
...
INFO: Sending host-config applied 1-c2bb5889f817c7ef8ec3b41a998863e642f89319a78377d5f455df6c68808da0
time="2015-08-24T15:43:14Z" level="info" msg="Starting event router." 
time="2015-08-24T15:43:14Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2015-08-24T15:43:14Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"0044d1fda7f0171e6879ec3d1ee05ac35f27381fceab2b8eae554c4c77deb29f\", From:\"-simulated-\", Time:0}" 
time="2015-08-24T15:43:14Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"a50d852abbf05a5cdf848a1c973da998561a1e344dd71e510469ef45bfd7976c\", From:\"-simulated-\", Time:0}" 
time="2015-08-24T15:43:14Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
time="2015-08-24T15:43:15Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
time="2015-08-24T15:43:16Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
time="2015-08-24T15:43:17Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
time="2015-08-24T15:43:18Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
time="2015-08-24T15:43:19Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
time="2015-08-24T15:43:20Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
time="2015-08-24T15:43:21Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=7 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
2015-08-24 15:43:22,344 ERROR cattle [139665405489392] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] ECONNREFUSED>
2015-08-24 15:43:22,353 ERROR cattle [139665405489392] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] ECONNREFUSED>
time="2015-08-24T15:43:22Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=8 reportedUuid="597fad29-e387-43bc-905f-2fa7daed9973" 
2015-08-24 15:43:23,340 ERROR cattle [139665405489392] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] ECONNREFUSED>
2015-08-24 15:43:23,344 ERROR cattle [139665405489392] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] ECONNREFUSED>
time="2015-08-24T15:43:23Z" level="info" msg="Connecting to proxy." url="ws://n179:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NDA0MzEzMDMsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjU5N2ZhZDI5LWUzODctNDNiYy05MDVmLTJmYTdkYWVkOTk3MyIsImlhdCI6MTQ0MDQzMTAwMywia2lkIjoiZGVmYXVsdCJ9.eCruEKfH4jkv-4z5CuFQpzThaY0JrEbkZ5MH0JCnVXiyJA4weSQRTn7Vvgfn_lyBme2BHkn9n_3O5A97BhLuKl4TJUI1wQ5OYgX2fBU0v4sHXDiTYPqBTVrIcjXzriux6x0myiuoVj4wDhUOLm9cFRb2NYWoGLlBJ5nIl0wXwSvXfnhyqHmypxDFyS8QVtVL0utuU2g_02kOAWPl4roneX9wnieEirwAM-KbDcjDsvbe5i52nSIQpdVkkxJatBzcPacHT_VtYZvvdoo59sIiuRW-YkIA3Zd7Yw1AOOQN947uA5MSMbNRF9dWMRm6IBPfLDJfiKBTgC7z1JFWP4cNeg" 
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
time="2015-08-24T15:43:25Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"613f0ed2d1b500e09f82988064050849ff5c31e0ee71838ec6813d38721524b4\", From:\"-simulated-\", Time:0}" 
time="2015-08-24T15:43:25Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"a50d852abbf05a5cdf848a1c973da998561a1e344dd71e510469ef45bfd7976c\", From:\"-simulated-\", Time:0}" 
time="2015-08-24T15:43:25Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"0044d1fda7f0171e6879ec3d1ee05ac35f27381fceab2b8eae554c4c77deb29f\", From:\"-simulated-\", Time:0}" 
time="2015-08-24T15:43:25Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"6b9eaa79c479969ecbb1effbdb8196d8b08763a84b6cda810c64719192147a26\", From:\"-simulated-\", Time:0}" 
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
nsenter: cannot open /host/proc/1/ns/mnt: No such file or directory
....
```

**Comment by bentolor** [comment]
Upgraded kernel & tried a fresh install; most errors dissappeared ...
